import React from 'react'

function Hero() {
    const style = {
        color: "red",
        // paddingTop: '10vh'
    }
    return (
        <div style={style}>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>
            <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nam voluptas, ipsam quisquam consequatur voluptatum nobis pariatur! Corporis eveniet facere accusantium aspernatur vel obcaecati? Quos error saepe a nemo expedita dolorum! Eum rem necessitatibus suscipit.</h1>

        </div>
    )
}

export default Hero
